### ISSUE TITLE
Cannot register or login: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by artur-gajewski** [mohiva/play-silhouette-seed#37]
I created a new VPS into which I planned to install my new application that uses Silhouette for user auth. In my laptop's dev environment and old VPS everything is working fine, but in this new VPS it seems like I have missed some crucial components that need to be installed in Linux. One of them was bcrypt which fixed one issue after installing it, but now I am facing another exception that I bet has something to do with other missing component. It did create the rows and everything in to the database but fails with the exceptions below.

I know this is an issue with my environment, but it would be nice to have a list of required components in system scope in order to use Silhouette :-)

For logging in:

    [StringIndexOutOfBoundsException: String index out of range: 16]
    In app/controllers/CredentialsAuthController.scala:57
    54        userService.retrieve(loginInfo).flatMap {
    55          case Some(user) => env.authenticatorService.create(user.loginInfo).flatMap { authenticator =>
    56            env.eventBus.publish(LoginEvent(user, request, request2lang))
    57            env.authenticatorService.init(authenticator).flatMap(v => env.authenticatorService.embed(v ,result))
    58          }
    59          case None => Future.failed(new AuthenticationException("Couldn't find user"))
    60        }
    61      }.recoverWith(exceptionHandler)
    62    )

For registration:

    [StringIndexOutOfBoundsException: String index out of range: 16]
    In app/controllers/SignUpController.scala:65
    62              user <- userService.save(user.copy(avatarURL = avatar))
    63              authInfo <- authInfoService.save(loginInfo, authInfo)
    64              authenticator <- env.authenticatorService.create(user.loginInfo)
    65              value <- env.authenticatorService.init(authenticator)
    66              result <- env.authenticatorService.embed(value, Future.successful(
    67                Redirect(routes.ApplicationController.index)
    68              ))
    69            } yield  {
    70              env.eventBus.publish(SignUpEvent(user, request, request2lang))

**Comment by artur-gajewski** [comment]
play.api.Application$$anon$1: Execution exception[[StringIndexOutOfBoundsException: String index out of range: 16]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.7.jar:2.3.7]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.4.jar:na]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 16
	at java.lang.String.substring(String.java:1907) ~[na:1.7.0_76]
	at play.api.libs.Crypto$.encryptAES(Crypto.scala:206) ~[play_2.11-2.3.7.jar:2.3.7]
	at com.mohiva.play.silhouette.impl.authenticators.SessionAuthenticatorService.com$mohiva$play$silhouette$impl$authenticators$SessionAuthenticatorService$$serialize(SessionAuthenticator.scala:279) ~[play-silhouette_2.11-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at com.mohiva.play.silhouette.impl.authenticators.SessionAuthenticatorService.init(SessionAuthenticator.scala:171) ~[play-silhouette_2.11-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at com.mohiva.play.silhouette.impl.authenticators.SessionAuthenticatorService.init(SessionAuthenticator.scala:103) ~[play-silhouette_2.11-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]

**Comment by akkie** [comment]
The only thing you need installed is Java and maybe SBT. BCrypt isn't necessary, because Silhouette uses a Java implementation of BCrypt.

It seems that your application secret isn't setup properly, because the error occures in the method [encryptAES](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/libs/Crypto.scala#L206), when it tries to get the first 16 chars form your application secret.

**Comment by artur-gajewski** [comment]
It seems that on OS X it seems to work with just "changeme" but on Linux I had to indeed make it atleast 16 characters. Thanks for your help!

**Comment by akkie** [comment]
OK, good that it works!
