### ISSUE TITLE
activator issue out of memory

### ISSUE THREAD

**Issue by nanothermite** [mohiva/play-silhouette-seed#77]
On Centos 6.7, activator 1.3.2, sbt 0.13.5, jdk 1.8.0_77, 32Gb desktop, using following sbtconfig.txt settings:

# Set the java args to high
-Xmx2048M
-XX:MaxPermSize=1024m
-XX:ReservedCodeCacheSize=512m
# Set the extra SBT options
-Dsbt.log.format=true
/opt/sbt/conf/sbtconfig.txt (END)

I get this when sending another request to the running instance on localhost:9000:

java.io.IOException: Cannot run program "sh": error=11, Resource temporarily unavailable                                  
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)                                                       
        at java.lang.Runtime.exec(Runtime.java:620)                                                                       
        at java.lang.Runtime.exec(Runtime.java:485)                                                                       
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:183)                                        
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:173)                                        
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:168)                                        
        at jline.internal.TerminalLineSettings.set(TerminalLineSettings.java:76)                                          
        at jline.internal.TerminalLineSettings.restore(TerminalLineSettings.java:68)                                      
        at jline.UnixTerminal.restore(UnixTerminal.java:66)                                                               
        at play.sbt.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:80)               
        at play.sbt.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:77)               
        at play.sbt.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:57)                           
        at play.sbt.PlayConsoleInteractionMode$.doWithoutEcho(PlayInteractionMode.scala:77)                               
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:117)         
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:52)          
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)                                                   
Caused by: java.io.IOException: error=11, Resource temporarily unavailable                                                
        at java.lang.UNIXProcess.forkAndExec(Native Method)                                                               
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)                                                             
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)                                                              
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)                                                       
        at java.lang.Runtime.exec(Runtime.java:620)                                                                       
        at java.lang.Runtime.exec(Runtime.java:485)                                                                       
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:183)                                        
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:173)                                        
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:168)                                        
        at jline.internal.TerminalLineSettings.set(TerminalLineSettings.java:76)                                          
        at jline.internal.TerminalLineSettings.restore(TerminalLineSettings.java:68)                                      
        at jline.UnixTerminal.restore(UnixTerminal.java:66)                                                               
        at play.sbt.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:80)               
        at play.sbt.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:77)               
        at play.sbt.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:57)                           
        at play.sbt.PlayConsoleInteractionMode$.doWithoutEcho(PlayInteractionMode.scala:77)                               
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:117)         
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:52)          
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)                                                   
[trace] Stack trace suppressed: run last compile:run for the full output.                                                 
[error] (compile:run) java.io.IOException: Cannot run program "sh": error=11, Resource temporarily unavailable            
[error] Total time: 71467 s, completed Apr 21, 2016 12:17:21 PM                                                           
1. Waiting for source changes... (press enter to interrupt)                                                               
sbt appears to be exiting abnormally.                                                                                     
  The log file for this session is at /tmp/sbt9213812969809295736.log                                                     
java.lang.OutOfMemoryError: unable to create new native thread                                                            
        at java.lang.Thread.start0(Native Method)                                                                         
        at java.lang.Thread.start(Thread.java:714)                                                                        
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)                                 
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)                                  
        at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)                      
        at sbt.CompletionService$.submit(CompletionService.scala:28)                                                      
        at sbt.ConcurrentRestrictions$$anon$4.submitValid(ConcurrentRestrictions.scala:160)                               
        at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:150)                                    
        at sbt.Execute.submit(Execute.scala:226)                                                                          
        at sbt.Execute.ready(Execute.scala:207)                                                                           
        at sbt.Execute.addNew(Execute.scala:181)                                                                          
        at sbt.Execute.addChecked(Execute.scala:163)                                                                      
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:185)                                                         
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:184)                                                         
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)                                                    
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                                                 
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                                             
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)                                                   
        at sbt.IDSet$$anon$1.foreach(IDSet.scala:35)                                                                      
        at sbt.Execute.addNew(Execute.scala:184)                                                                          
        at sbt.Execute.addChecked(Execute.scala:163)                                                                      
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:185)                                                         
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:184)                                                         
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)                                                    
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                                                 
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                                             
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)                                                   
        at sbt.IDSet$$anon$1.foreach(IDSet.scala:35)                                                                      
        at sbt.Execute.addNew(Execute.scala:184)                                                                          
        at sbt.Execute.addChecked(Execute.scala:163)                                                                      
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:185)                                                         
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:184)                                                         
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)                                                    
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                                                 
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                                             
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)                                                   
        at sbt.IDSet$$anon$1.foreach(IDSet.scala:35)                                                                      
        at sbt.Execute.addNew(Execute.scala:184)                                                                          
        at sbt.Execute.addChecked(Execute.scala:163)                                                                      
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:185)                                                         
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:184)                                                         
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)                                                    
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                                                 
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                                             
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)                                                   
        at sbt.IDSet$$anon$1.foreach(IDSet.scala:35)                                                                      
        at sbt.Execute.addNew(Execute.scala:184)                                                                          
        at sbt.Execute.addChecked(Execute.scala:163)                                                                      
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:185)                                                         
        at sbt.Execute$$anonfun$addNew$3.apply(Execute.scala:184)                                                         
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)                                                    
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                                                 
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                                             
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)                                                   
        at sbt.IDSet$$anon$1.foreach(IDSet.scala:35)                                                                      
        at sbt.Execute.addNew(Execute.scala:184)                                                                          
        at sbt.Execute.runKeep(Execute.scala:65)                                                                          
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:342)                                                        
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:341)                                                                
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)                                                              
        at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)                               
        at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)                               
        at scala.Option$WithFilter.map(Option.scala:206)                                                                  
        at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:258)                                                
        at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:257)                                                
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)                                                          
        at sbt.EvaluateTask$.apply(EvaluateTask.scala:257)                                                                
        at sbt.EvaluateTask$.apply(EvaluateTask.scala:255)                                                                
        at sbt.EvaluateTask$.evaluateTask(EvaluateTask.scala:238)                                                         
        at sbt.Defaults$$anonfun$watchSetting$1$$anon$1.watchPaths(Defaults.scala:333)                                    
        at sbt.Watched$$anonfun$4.apply(Watched.scala:52)                                                                 
        at sbt.Watched$$anonfun$4.apply(Watched.scala:52)                                                                 
        at sbt.PathFinder$$anon$2.addTo(Path.scala:87)                                                                    
        at sbt.PathFinder.get(Path.scala:158)                                                                             
        at sbt.SourceModificationWatch$.watch(SourceModificationWatch.scala:13)
        at sbt.Watched$.liftedTree1$1(Watched.scala:60)
        at sbt.Watched$.executeContinuously(Watched.scala:59)
        at sbt.BasicCommands$$anonfun$continuous$1$$anonfun$apply$10.apply(BasicCommands.scala:142)
        at sbt.BasicCommands$$anonfun$continuous$1$$anonfun$apply$10.apply(BasicCommands.scala:140)
        at sbt.CommandUtil$.withAttribute(CommandUtil.scala:33)
        at sbt.BasicCommands$$anonfun$continuous$1.apply(BasicCommands.scala:140)
        at sbt.BasicCommands$$anonfun$continuous$1.apply(BasicCommands.scala:139)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.OutOfMemoryError: unable to create new native thread

What settings do you folks use?

Thanks,
Henry

**Comment by akkie** [comment]
Please do not use the issue tracker for questions! Anyway this is a general Play Framework question. So the [Play Framework mailing list](https://groups.google.com/forum/#!forum/play-framework) should be the right place for such question.
